version: '3.7'

services:
  app:
    image: pspc/ecency-boilerplate:latest
    ports:
      - "80:3000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.9"
          memory: 500M
      update_config:
        parallelism: 4
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
